# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='champ_images')),
                ('q_skill', models.CharField(max_length=32)),
                ('w_skill', models.CharField(max_length=32)),
                ('e_skill', models.CharField(max_length=32)),
                ('r_skill', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champion_picker.Champion')),
                ('items', models.ManyToManyField(related_name='items', to='champion_picker.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=30)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('minions_killed', models.IntegerField()),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='champion_picker.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='WinRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=30)),
                ('role1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role1', to='champion_picker.Role')),
                ('role2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role2', to='champion_picker.Role')),
            ],
        ),
    ]
