# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champion_picker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembuild',
            name='champion',
        ),
        migrations.AddField(
            model_name='itembuild',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='champion_picker.Role'),
            preserve_default=False,
        ),
    ]
