# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion_picker', '0003_auto_20160413_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='lane',
            field=models.CharField(default='', max_length=32),
        ),
    ]
