# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champion_picker', '0004_role_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='lane',
        ),
    ]
